Sprint 6/step 1
marlibon/react-burger pull request #8
Opened 2024-02-10 15:30 UTC by marlibon

2024-02-10 16:29 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Практически все юнит-тесты проходят успешно
- В readme есть ссылка на проект.

### **Есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/8FT7DKKTUjdYjA> - Ошибка в тесте `app.test.js`. Есть подозрения, что у не совпадает версия nodejs. Укажите в комментариях какая у вас версия `nodejs`;

- У вас падает `cypress` тест <https://disk.yandex.com/i/GuTh9hf-m0PX2A>;

### **Сделает код лучше:**

- Чтобы проверить процент покрытия тестами всех файлов, используйте команду `react-scripts test --coverage --watchAll`

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>;

2024-02-10 16:29 UTC, ArslanMustafin commented on cypress/e2e/modal.cy.ts
> +        cy.get("[data-cy='Флюоресцентная булка R2-D3']").click();
**Надо исправить:**

Не стоит использовать русские названия для `data-cy`. Лучше  написать так: `cy.contains('Флюоресцентная булка R2-D3').click()`. 

И далее внизу проверьте, точно ли у вас стоят такие `data-cy` у элементов;

2024-02-10 16:29 UTC, ArslanMustafin commented on cypress/e2e/order.cy.ts
> +    cy.get(`[data-cy='${main}']`).click();
**Надо исправить:**

Здесь и далее.

Не стоит использовать русские названия для data-cy. Лучше написать так: `cy.contains(main).click()`.

2024-02-10 16:29 UTC, ArslanMustafin commented on src/components/app/app.test.js
> +});
**Можно лучше:**

не думаю что тут нужен этот тест;

2024-02-12 17:20 UTC, marlibon commented on cypress/e2e/modal.cy.ts
> +        cy.get("[data-cy='Флюоресцентная булка R2-D3']").click();
отказался от этого теста, т.к. модальное окно проверяется в основном тесте e2e

2024-02-12 17:35 UTC, marlibon commented on cypress/e2e/order.cy.ts
> +    cy.get(`[data-cy='${main}']`).click();
поправил

2024-02-12 17:35 UTC, marlibon commented on src/components/app/app.test.js
> +});
удалил

2024-02-13 09:34 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.🔥

### **Вы молодец! Работа принята.**

Несколько советов для дальнейшего развития:

- Сверстайте несколько небольших проектов для себя, для закрепления знаний, и чтобы можно добавить их в портфолио.

- Ходите на собеседования: опыт прохождения собеседований не менее важен знаний теории, и Вы поймете, какие знания требуются на рынке, и где Вы проседаете.

- Читайте habr и слушаете подкаксты: они очень хорошо расширяют кругозор и позволяют узнать, что происходит в отрасли.

2024-02-16 04:39 UTC, merged